services:
  - type: web
    name: rul-prediction-api
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: pip install -e .
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT
    plan: free
